/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * Scene.ls
 */
export class RuntimeScriptBase extends Laya.Scene {
    public click!: Laya.Button;
    public score!: Laya.Label;
    public autoClickButton!: Laya.Button;
    public clickPowerButton!: Laya.Button;
    public autoClickLabel!: Laya.Label;
    public clickPowerLabel!: Laya.Label;
}

